### ISSUE TITLE
Options Type Improvements

### ISSUE THREAD

**Issue by shellscape** [activeguild/esbuild-plugin-prismjs#7]
This is the current typing for `PluginOptions`:

```ts
declare type PluginOptions = {
    languages: string | string[];
    plugins: string[];
    theme: string;
    css: true;
    inline?: boolean;
};
```

 Which requires way more on the part of the user than is necessary. A better typing would be:
 
 ```ts
 declare type PluginOptions = {
    languages: string | string[];
    plugins?: string[];
    theme?: string;
    inline?: boolean;
};
```

And setting the defaults for the options not passed in the object. The fact that `css: true` is in that typing is problematic enough.

**Comment by activeguild** [comment]
@shellscape 
I fixed it and published a new version.

**Comment by shellscape** [comment]
👍 thanks!
